<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        body { font-family: 'Helvetica', sans-serif; font-size: 13px; color: #222; margin: 30px; }
        .header { text-align: center; margin-bottom: 20px; border-bottom: 2px solid #3271a8; padding-bottom: 14px; }
        .header h2 { margin: 0; font-size: 18px; color: #1b212a; }
        .header small { color: #666; font-size: 12px; }
        table { width: 100%; border-collapse: collapse; margin-top: 16px; }
        td { padding: 7px 10px; border-bottom: 1px solid #e0e0e0; font-size: 12px; }
        td:first-child { color: #555; width: 55%; }
        td:last-child { text-align: right; font-weight: 600; font-family: monospace; }
        .total td { border-top: 2px solid #3271a8; font-size: 14px; font-weight: 700; padding-top: 10px; }
        .footer { text-align: center; margin-top: 24px; color: #999; font-size: 10px; }
    </style>
</head>
<body>
    <div class="header">
        <h2>Daily Sales Report</h2>
        <small>{{ $report->report_date->format('l, F j, Y') }}</small>
    </div>
    <table>
        <tr><td>Gross Revenue</td><td>${{ number_format($report->gross_revenue, 2) }}</td></tr>
        <tr><td>Total Expenses (COGS)</td><td>${{ number_format($report->total_expenses, 2) }}</td></tr>
        <tr class="total"><td>Net Profit</td><td>${{ number_format($report->net_profit, 2) }}</td></tr>
        <tr><td>Tax Collected</td><td>${{ number_format($report->total_tax_collected, 2) }}</td></tr>
    </table>
    <table>
        <tr><td>Total Transactions</td><td>{{ $report->total_transactions }}</td></tr>
        <tr><td>Cash Transactions</td><td>{{ $report->cash_count }}</td></tr>
        <tr><td>Card Transactions</td><td>{{ $report->card_count }}</td></tr>
    </table>
    <div class="footer">Generated by POS System &mdash; {{ now()->format('M d, Y h:i A') }}</div>
</body>
</html>
